export { HomePage } from "./HomePage";
export { Dashboard } from "./Dashboard";
export { Test } from "./Test";
export { Terms } from "./Terms";
export { Contact } from "./Contact";
export { Privacy } from "./Privacy";
export { About } from "./About";
export { News } from "./News";
export { Article } from "./Article";
